name: Test contract

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.63
        with:
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - run: cargo test
